objects/Account.object
<CustomObject>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>Silver</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription_duration__c</fullName>
        <label>Subscription Duration</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Subscription__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annual</fullName>
                </value>
                <value>
                    <fullName>Annual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Subscription__c</fullName>
        <formula>TEXT(Account.Subscription__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subscription</label>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Brand</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/Product_list__c.object
<CustomObject>
    <label>Product list</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Product list No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Product lists</relationshipLabel>
        <relationshipName>Product_lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product lists</relationshipLabel>
        <relationshipName>Product_lists</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

globalValueSets/Brand.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Croma</fullName>
    </customValue>
    <customValue>
        <fullName>One Plus</fullName>
    </customValue>
    <customValue>
        <fullName>Samsung</fullName>
    </customValue>
    <customValue>
        <fullName>Panasonic</fullName>
    </customValue>
    <customValue>
        <fullName>Sony</fullName>
    </customValue>
    <customValue>
        <fullName>BPL</fullName>
    </customValue>
    <customValue>
        <fullName>LG</fullName>
    </customValue>
    <customValue>
        <fullName>HP</fullName>
    </customValue>
    <customValue>
        <fullName>DELL</fullName>
    </customValue>
    <customValue>
        <fullName>Apple</fullName>
    </customValue>
    <customValue>
        <fullName>Epson</fullName>
    </customValue>
    <customValue>
        <fullName>Canon</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>Nokia</fullName>
    </customValue>
    <customValue>
        <fullName>Poco</fullName>
    </customValue>
    <customValue>
        <fullName>Zebronics</fullName>
    </customValue>
    <customValue>
        <fullName>Egate</fullName>
    </customValue>
    <customValue>
        <fullName>Wanbo</fullName>
    </customValue>
    <customValue>
        <fullName>Shopexo</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Brand</masterLabel>
</GlobalValueSet>

globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>Printer</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Projector</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

classes/Productlist.cls
public without sharing class Productlist {
   
    @AuraEnabled(cacheable = true)
    public  static List<Product_list__c> ProductData(string accName) {
        
        System.debug('Name Account'+accName);

        // List<ServiceKA__Product_list__c> Productlist = [SELECT id,ServiceKA__Account__r.Name,ServiceKA__Product__r.ServiceKA__Product_Category__c ,
        //         ServiceKA__Product__r.ServiceKA__Brand__c,ServiceKA__Product__r.Name
        //     from ServiceKA__Product_list__c where ServiceKA__Account__r.Name = :accName ];


            List<Product_list__c> Productlist1= [ SELECT Id,Contact__r.Id,Contact__r.Name,Contact__r.Account.Subscription_duration__c ,Contact__r.Subscription__c,Contact__r.Phone,Contact__r.Email,Contact__r.AccountId,Contact__r.Account.Name , Product__r.Product_Category__c,Product__r.Brand__c,Product__r.Name FROM Product_list__c
                  where Contact__r.Account.Name = :accName ];

        System.debug('Product list'+Productlist1);

        return  Productlist1;
        
    }

    @AuraEnabled(cacheable = true)
    public  static List<Contact> ContactData(String accName) {
        return [SELECT Id,Name,Account.Subscription__c,Account.Name, Account.Subscription_duration__c,Phone,Email FROM Contact where Account.Name=:accName ];

    }

    @AuraEnabled(cacheable=true)
    public static User getUserDetails(Id recId) {
    try{
    user userrec;
    if(recId != null || recId != '')
    { 
    userrec =  [SELECT Id,Name,AccountId,ContactId,Email,Username,ProfileId,Profile.Name
                  ,Account.Name FROM User where Id =:recId];
    }
    return userrec;
    } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

	
      @AuraEnabled(cacheable = true)
       public static  List<Contact> getContactData(String UserName){
           Return [SELECT Id,Name,Account.Name FROM Contact WHERE Name = :UserName];

       }

     // Milestone
@AuraEnabled(cacheable=true)
public static list<Entitlement> getEntitlement(string name){
      
 string searchKeyword = '%' + name + '%';

 list<Entitlement> entitlementlist = new list<Entitlement>();
System.debug('Entitlement Name :' +searchKeyword);

for(Entitlement knowObj : [SELECT Id,Name From Entitlement  WHERE Name = :name ]){

                                  entitlementlist.add(knowObj);

     }
     return entitlementlist;
}
}