objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <inlineHelpText>Support-If you are facing issue or question&apos;s related to Return &amp; Refunds, Shipping &amp; Tracking, Delivery, Order issues and Orders then you can submit case by selecting case type &apos;Support&apos;./ Request-If you are facing technical issue or question&apos;s related to Phone &amp; Tablets, Desktop &amp; PC, Earphones and Headphones,Digital Watch then you can submit case by selecting case type &apos;Request&apos;./ Other-If you are facing any issue other than &apos;Support&apos; &amp; &apos;Request&apos; then you can submit case by selecting case type &apos;Other&apos;.</inlineHelpText>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>cate__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Repairs &amp; Physical Damage</fullName>
                </value>
                <value>
                    <fullName>Device Performance</fullName>
                </value>
                <value>
                    <fullName>Update, Backup, restore</fullName>
                </value>
                <value>
                    <fullName>Passwords &amp; Security</fullName>
                </value>
                <value>
                    <fullName>Subscriptions &amp; Purchases</fullName>
                </value>
                <value>
                    <fullName>Camera</fullName>
                </value>
                <value>
                    <fullName>Apps &amp; Software</fullName>
                </value>
                <value>
                    <fullName>Battery &amp; Power</fullName>
                </value>
                <value>
                    <fullName>Physical or Liquid Damage</fullName>
                </value>
                <value>
                    <fullName>Internet</fullName>
                </value>
                <value>
                    <fullName>Accessories</fullName>
                </value>
                <value>
                    <fullName>Sound</fullName>
                </value>
                <value>
                    <fullName>Battery &amp; Charging</fullName>
                </value>
                <value>
                    <fullName>Pairing Connectivity</fullName>
                </value>
                <value>
                    <fullName>Audio &amp; Sound</fullName>
                </value>
                <value>
                    <fullName>Health &amp; Fitness</fullName>
                </value>
                <value>
                    <fullName>Pairing &amp; Connectivity</fullName>
                </value>
                <value>
                    <fullName>Bands &amp; Accessories</fullName>
                </value>
                <value>
                    <fullName>Setup &amp; Usage</fullName>
                </value>
                <value>
                    <fullName>Battery, Power &amp; Charging</fullName>
                </value>
                <value>
                    <fullName>Return Purchase</fullName>
                </value>
                <value>
                    <fullName>Exchange</fullName>
                </value>
                <value>
                    <fullName>Return Gift Item</fullName>
                </value>
                <value>
                    <fullName>Refund time</fullName>
                </value>
                <value>
                    <fullName>Delivery Time</fullName>
                </value>
                <value>
                    <fullName>Track order</fullName>
                </value>
                <value>
                    <fullName>Shipping Charges</fullName>
                </value>
                <value>
                    <fullName>Remove Label</fullName>
                </value>
                <value>
                    <fullName>Wrong Delivery</fullName>
                </value>
                <value>
                    <fullName>Delivery Not Received</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>cate__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Case_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Phone and Tablets</fullName>
                </value>
                <value>
                    <fullName>Desktop and PC</fullName>
                </value>
                <value>
                    <fullName>Earphones &amp; Headphones</fullName>
                </value>
                <value>
                    <fullName>Return &amp; Refunds</fullName>
                </value>
                <value>
                    <fullName>Digital Watch</fullName>
                </value>
                <value>
                    <fullName>Shipping &amp; Tracking</fullName>
                </value>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>Order Issues</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

classes/TestCaseController.cls
@isTest
private class TestCaseController {
    
    @isTest  static void TestMethod1(){
        List<Case> caseRecList = new List<Case>();
        
        Case caselist = new Case(Subject='Phone enquiry',Description='Check battery',
                                cate__c='Delivery',Case_Type__c='Support',
                              Sub_Category__c='Delivery Time' );
        caseRecList.add(caselist);
        
       insert caseRecList;  
        
        for(case c : caseRecList){
             CaseController.saveFile(c.id,'File Test ','base64Data') ;
        }
       // ContentVersion saveFile(Id idParent, String strFileName, String base64Data) {
    }
}