objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <inlineHelpText>Support-If you are facing issue or question&apos;s related to Return &amp; Refunds, Shipping &amp; Tracking, Delivery, Order issues and Orders then you can submit case by selecting case type &apos;Support&apos;./ Request-If you are facing technical issue or question&apos;s related to Phone &amp; Tablets, Desktop &amp; PC, Earphones and Headphones,Digital Watch then you can submit case by selecting case type &apos;Request&apos;./ Other-If you are facing any issue other than &apos;Support&apos; &amp; &apos;Request&apos; then you can submit case by selecting case type &apos;Other&apos;.</inlineHelpText>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                </value>
                <value>
                    <fullName>Support</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>cate__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Repairs &amp; Physical Damage</fullName>
                </value>
                <value>
                    <fullName>Device Performance</fullName>
                </value>
                <value>
                    <fullName>Update, Backup, restore</fullName>
                </value>
                <value>
                    <fullName>Passwords &amp; Security</fullName>
                </value>
                <value>
                    <fullName>Subscriptions &amp; Purchases</fullName>
                </value>
                <value>
                    <fullName>Camera</fullName>
                </value>
                <value>
                    <fullName>Apps &amp; Software</fullName>
                </value>
                <value>
                    <fullName>Battery &amp; Power</fullName>
                </value>
                <value>
                    <fullName>Physical or Liquid Damage</fullName>
                </value>
                <value>
                    <fullName>Internet</fullName>
                </value>
                <value>
                    <fullName>Accessories</fullName>
                </value>
                <value>
                    <fullName>Sound</fullName>
                </value>
                <value>
                    <fullName>Battery &amp; Charging</fullName>
                </value>
                <value>
                    <fullName>Pairing Connectivity</fullName>
                </value>
                <value>
                    <fullName>Audio &amp; Sound</fullName>
                </value>
                <value>
                    <fullName>Health &amp; Fitness</fullName>
                </value>
                <value>
                    <fullName>Pairing &amp; Connectivity</fullName>
                </value>
                <value>
                    <fullName>Bands &amp; Accessories</fullName>
                </value>
                <value>
                    <fullName>Setup &amp; Usage</fullName>
                </value>
                <value>
                    <fullName>Battery, Power &amp; Charging</fullName>
                </value>
                <value>
                    <fullName>Return Purchase</fullName>
                </value>
                <value>
                    <fullName>Exchange</fullName>
                </value>
                <value>
                    <fullName>Return Gift Item</fullName>
                </value>
                <value>
                    <fullName>Refund time</fullName>
                </value>
                <value>
                    <fullName>Delivery Time</fullName>
                </value>
                <value>
                    <fullName>Track order</fullName>
                </value>
                <value>
                    <fullName>Shipping Charges</fullName>
                </value>
                <value>
                    <fullName>Remove Label</fullName>
                </value>
                <value>
                    <fullName>Wrong Delivery</fullName>
                </value>
                <value>
                    <fullName>Delivery Not Received</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>cate__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Case_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Phone and Tablets</fullName>
                </value>
                <value>
                    <fullName>Desktop and PC</fullName>
                </value>
                <value>
                    <fullName>Earphones &amp; Headphones</fullName>
                </value>
                <value>
                    <fullName>Return &amp; Refunds</fullName>
                </value>
                <value>
                    <fullName>Digital Watch</fullName>
                </value>
                <value>
                    <fullName>Shipping &amp; Tracking</fullName>
                </value>
                <value>
                    <fullName>Delivery</fullName>
                </value>
                <value>
                    <fullName>Order Issues</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>Printer</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Projector</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

classes/TestSkillBasedRoutingClass.cls
@IsTest
public class TestSkillBasedRoutingClass {
    @isTest  
    static void Testmethod1(){
     
      List<Case> caseRecList = new List<Case>();
        List<Skill> allSkillsInDB = [SELECT id,MasterLabel from Skill];
        
    Case caselist = new Case(Subject='Phone enquiry',Description='Check battery',
                               cate__c='Delivery',Case_Type__c='Support',
                              Sub_Category__c='Delivery Time',Product_Category__c='Printer' );
        caseRecList.add(caselist);
    insert caseRecList;
    
    List<String> caseId = new List<String>();
    for(Case caseRec : caseRecList){
          PendingServiceRouting psr = new PendingServiceRouting(
            CapacityWeight = 1,
            IsReadyForRouting = FALSE,
            RoutingModel  = 'MostAvailable',
            RoutingPriority = 1,
            RoutingType = 'SkillsBased',
            ServiceChannelId = '0N95j000000H8jS',
            WorkItemId =caseRec.Id
          );
        SkillRequirement skillRequ = new SkillRequirement();
                skillRequ.SkillId = '0C55j000000Cb2dCAC';
                skillRequ.RelatedRecordId = psr.id;
                skillRequ.SkillLevel = 5;
                insert skillRequ;
        caseId.add(caseRec.Id);
       insert psr; 
        
        
    
        
        //SkillBasedRoutingClass.routingCasesToAgents(caseId);
        
        
         /** //FIND OUT THE SKILLS REQUIRED FOR A GIVEN CASE BASED ON ITS CATEGORY
            List<String> matchingSkillIds = new List<String>();
            for(Skill skillRec: allSkillsINDB){
                if(caseRec.ServiceKA__cate__c.contains(skillRec.MasterLabel)){
                    matchingSkillIds.add(skillRec.Id);
                }
            }
        
          List<SkillRequirement> skillReqsToInsert = new List<SkillRequirement>();
            //Associate matching skills with PSR request
            for(String matchingSkillId: matchingSkillIds){
                SkillRequirement skillRequ = new SkillRequirement();
                skillRequ.SkillId = matchingSkillId;
                skillRequ.RelatedRecordId = psr.id;
                skillRequ.SkillLevel = 5;
                skillReqsToInsert.add(skillRequ);
            }
            Insert skillReqsToInsert;
        
        psr.IsReadyForRouting = TRUE; 
            Update PSR;**/
        SkillBasedRoutingClass.routingCasesToAgents(caseId);
       // PendingServiceRouting ppsr = new PendingServiceRouting();
            //system.assertEquals(true, ppsr.IsReadyForRouting);
    }
        
    }
   
         /** list<Case> lstcase = new list<Case>();
        list<string> caseid = new list<string>();
        for(integer i=1; i>10; i++)
        {Case caselist = new Case(Subject='Phone enquiry'+i,Description='Check battery',
                                ServiceKA__cate__c='Delivery',ServiceKA__Case_Type__c='Support',
                                  ServiceKA__Sub_Category__c='Delivery Time' );
         lstcase.add(caselist);
        }
        insert lstcase;
        for (case cs: lstcase){
            caseid.add(cs.id);
        }
        SkillBasedRoutingClass.routingCasesToAgents(caseid);
       // PendingServiceRouting ppsr = new PendingServiceRouting();
          //  system.assertEquals(true, ppsr.IsReadyForRouting);**/
    }