objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Priority__c</fullName>
        <formula>IF((TODAY() - DATEVALUE(CreatedDate))&lt;=1,&apos;Low&apos;,
 IF((TODAY() - DATEVALUE(CreatedDate))&gt;1 &amp;&amp; (TODAY() - DATEVALUE(CreatedDate))&lt;1.5 ,&apos;Medium&apos;,
 IF((TODAY() - DATEVALUE(CreatedDate))&gt;=1.5,&apos;High&apos;, &apos;Very High&apos; )))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Priority</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Resolution_Comment__c</fullName>
        <label>Resolution Comment</label>
        <type>TextArea</type>
    </fields>
</CustomObject>

globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>Printer</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Projector</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

classes/CaseEmails.cls
public with sharing class CaseEmails {
    
  @AuraEnabled(cacheable= true)
    public  static  List<Schema.EmailMessage>  CaseEmailMessage(string recordId) {
                   String Id = '5005j00000Of79UAAR';
            // fuller query
             List<Schema.EmailMessage> msg=  [Select ParentId,FromName,TextBody,CreatedDate From EmailMessage where ParentId=:recordId];  
            return msg;
    }

    @AuraEnabled(cacheable= true)
    public static List<Case> CaseDetails(string recordId){
      return [Select Id,CaseNumber,Owner.Name,Status,Case_Priority__c, Product_Category__c,Resolution_Comment__c,Subject FROM Case  where Id=:recordId];
    }

    @AuraEnabled(cacheable= true)
    public  static  List<CaseComment>  CaseComment(string recordId) {
                  string casecreatedDate,CommentBody,Name,ParentId,CaseId;
                   List<String> casecmmt = new List<String>();
            // fuller query
             List<CaseComment> msg=  [SELECT Id,ParentId,CreatedBy.Name,CommentBody,CreatedDate FROM CaseComment where ParentId=:recordId order by CreatedDate asc];    
            return msg ;
    }

  }