objects/Knowledge__kav.object
<CustomObject>

    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>20000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product_Category</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Catalogue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service Catalogue</label>
        <referenceTo>Service_Catalogue__c</referenceTo>
        <relationshipLabel>Knowledge</relationshipLabel>
        <relationshipName>Knowledge</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Service_Catalogue__c.object
<CustomObject>
    <label>Service Catalogue</label>
    <nameField>
        <label>Service Catalogue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Catalogues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/Product_Category.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>TV</fullName>
    </customValue>
    <customValue>
        <fullName>Printer</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile</fullName>
    </customValue>
    <customValue>
        <fullName>Projector</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Product Category</masterLabel>
</GlobalValueSet>

classes/TVKnowledgearticle.cls
public with sharing class TVKnowledgearticle {
 @AuraEnabled(cacheable=true)
    public static list<Knowledge__kav> getKnowledgeList() { 

         // create knowledge article list to store search result 
         list<Knowledge__kav> knowledgeListRecord = new list<Knowledge__kav>();
      //   list<knowledge__kav> knowledgeListRecord = new list<knowledge__kav>();

         for(Knowledge__kav knowObj : [SELECT Id,Title,Product_Category__c,Answer__c,ValidationStatus,
                 Service_Catalogue__r.Name From Knowledge__kav  WHERE Product_Category__c = 'Tv']){

            knowledgeListRecord.add(knowObj);
 
       } 

     return knowledgeListRecord;
 }
}